export let companyData = [
  {
    job: "웹디자이너",
    name: "무신사",
    speed: "응답률 매우 높음",
    region: "서울·한국",
    compensation: "채용보상금 1,000,000원",
  },
  {
    job: "채용 담당자",
    name: "우아한청년들",
    speed: "응답률 매우 높음",
    region: "서울·한국",
    compensation: "채용보상금 1,000,000원",
  },
  {
    job: "프론트엔드",
    name: "원티드",
    speed: "응답률 매우 높음",
    region: "서울·한국",
    compensation: "채용보상금 1,000,000원",
  },
  {
    job: "백엔드",
    name: "삼성",
    speed: "응답률 매우 높음",
    region: "서울·한국",
    compensation: "채용보상금 1,000,000원",
  },
  {
    job: "웹디자이너",
    name: "무신사",
    speed: "응답률 매우 높음",
    region: "서울·한국",
    compensation: "채용보상금 1,000,000원",
  },
  {
    job: "프론트엔드",
    name: "원티드",
    speed: "응답률 매우 높음",
    region: "서울·한국",
    compensation: "채용보상금 1,000,000원",
  },
  {
    job: "웹디자이너",
    name: "무신사",
    speed: "응답률 매우 높음",
    region: "서울·한국",
    compensation: "채용보상금 1,000,000원",
  },
  {
    job: "웹디자이너",
    name: "무신사",
    speed: "응답률 매우 높음",
    region: "서울·한국",
    compensation: "채용보상금 1,000,000원",
  },
  {
    job: "웹디자이너",
    name: "무신사",
    speed: "응답률 매우 높음",
    region: "서울·한국",
    compensation: "채용보상금 1,000,000원",
  },
  {
    job: "웹디자이너",
    name: "무신사",
    speed: "응답률 매우 높음",
    region: "서울·한국",
    compensation: "채용보상금 1,000,000원",
  },
  {
    job: "웹디자이너",
    name: "무신사",
    speed: "응답률 매우 높음",
    region: "서울·한국",
    compensation: "채용보상금 1,000,000원",
  },
  {
    job: "웹디자이너",
    name: "무신사",
    speed: "응답률 매우 높음",
    region: "서울·한국",
    compensation: "채용보상금 1,000,000원",
  },
  {
    job: "웹디자이너",
    name: "무신사",
    speed: "응답률 매우 높음",
    region: "서울·한국",
    compensation: "채용보상금 1,000,000원",
  },
  {
    job: "웹디자이너",
    name: "무신사",
    speed: "응답률 매우 높음",
    region: "서울·한국",
    compensation: "채용보상금 1,000,000원",
  },
  {
    job: "웹디자이너",
    name: "무신사",
    speed: "응답률 매우 높음",
    region: "서울·한국",
    compensation: "채용보상금 1,000,000원",
  },
  {
    job: "웹디자이너",
    name: "무신사",
    speed: "응답률 매우 높음",
    region: "서울·한국",
    compensation: "채용보상금 1,000,000원",
  },
  {
    job: "웹디자이너",
    name: "무신사",
    speed: "응답률 매우 높음",
    region: "서울·한국",
    compensation: "채용보상금 1,000,000원",
  },
  {
    job: "웹디자이너",
    name: "무신사",
    speed: "응답률 매우 높음",
    region: "서울·한국",
    compensation: "채용보상금 1,000,000원",
  },
  {
    job: "웹디자이너",
    name: "무신사",
    speed: "응답률 매우 높음",
    region: "서울·한국",
    compensation: "채용보상금 1,000,000원",
  },
  {
    job: "웹디자이너",
    name: "무신사",
    speed: "응답률 매우 높음",
    region: "서울·한국",
    compensation: "채용보상금 1,000,000원",
  },
];

export let socialData = [
  {
    img: process.env.PUBLIC_URL + "/apple.png",
    name: "Apple",
  },
  {
    img: process.env.PUBLIC_URL + "/facebook.png",
    name: "Facebook",
  },
  {
    img: process.env.PUBLIC_URL + "/google.png",
    name: "Google",
  },
  {
    img: process.env.PUBLIC_URL + "/kakao.png",
    name: "Kakao",
  },
];
